//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitedReporting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string AttorneyFirstName { get; set; }
        public string AttorneyLastName { get; set; }
        public string FirmName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string CaseNumber { get; set; }
        public string CaseName { get; set; }
        public string PreceedingDate { get; set; }
        public string RequestedServices { get; set; }
        public string NoticeFilePath { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Message { get; set; }
    }
}
