//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitedReporting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranscriptOrder
    {
        public int Id { get; set; }
        public string OrderingAttorney { get; set; }
        public string FirmName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string CaseStyle { get; set; }
        public string DateTaken { get; set; }
        public string DeponentsOrJudge { get; set; }
        public string DateNeeded { get; set; }
        public string Excerpt { get; set; }
    }
}
